### ISSUE TITLE
Alternative project: oldssl-proxy

### ISSUE THREAD

**Issue by ValdikSS** [ticky/mitmproxy-oldssl#1]
I've searched the internet pretty hard, but managed to discover your project only after I made my own.
https://bitbucket.org/ValdikSS/oldssl-proxy/
https://hub.docker.com/r/valdikss/oldssl-proxy

Compared to yours, it uses squid in ssl-bump mode, which is a little less hackish since it "properly supports" SNI (it uses domain in proxy CONNECT request as the domain name).

Also found another project: https://github.com/atauenis/webone

**Comment by ticky** [comment]
Neat! I'm sure there are plenty of other ways to do this.

> it uses domain in proxy CONNECT request as the domain name

That's exactly what my `unsafe_sni` plugin does, too, with the goal of still respecting and handling SNI on the proxy server side :)

Webone seems neat, but it's fiddly to run on Unix, and I wanted to preserve whatever SSL support the client had, so its "make everything plaintext" approach didn't sit right with me.
